### ISSUE TITLE
Verify full openapi swagger can still be parsed.

### ISSUE THREAD

**Issue by seans3** [kubernetes/kube-openapi#103]
This issue is moved from kubectl repo.

Since kubernetes/kube-openapi#10 is moving parsing code for openapi from the main repo to https://github.com/kubernetes/kube-openapi/, we need to verify that the full swagger openapi file can still be parsed.

This is just a reminder that we need to do that.
In other word, we need to add a test in the main repo that verifies that the parsing code can parse the openapi swagger.

**Comment by apelisse** [comment]
[This PR](https://github.com/kubernetes/kube-openapi/pull/78) is the foundation block to fix this issue.
It's building an integration test so that we can make sure all the steps are working fine, including parsing the generated `swagger.json`.

If anybody wants to work on this, I'd be happy to provide guidance

/help
/unassign
