### ISSUE TITLE
Expand coverage/support for atomics

### ISSUE THREAD

**Issue by jpbetz** [kubernetes/kube-openapi#203]
We have a bunch of cases involving the composition of atomics that we don't yet test.

We need to define and test the behavior of all of them. Creating a grid out all possible combinations might be a good first step.

Here are a few we are aware of:

#### map typeref is tagged with +mapType=atomic (not supported or tested)

```go
type Container struct {
  Field AtomicMapTyperef
}

// +mapType=atomic
type AtomicMapTyperef map[string]string
```

#### reference to map typeref is tagged with +mapType=atomic (not tested, seems to work)

```go
type Container struct {
  //+mapType=atomic
  Field AtomicMapTyperef
}

type AtomicMapTyperef map[string]string
```

#### set of atomic structs (not tested, not sure if it works)

```go
type Container struct {
  //+listType=set
  SetField []AtomicStruct
}

//+mapType=atomic
type AtomicStruct struct {
  StringField string
}
```

#### map value is atomic struct (not tested, not sure if it works)

```go
type Container struct {
  //+listType=map
  //+listMapKey=name
  ListField []ListItem
}

//+mapType=atomic
type ListItem struct {
  Name string
  AtomicStructField AtomicStruct
}

//+mapType=atomic
type AtomicStruct struct {
  StringField string
}
```

#### map key is atomic struct (not tested, not sure if it works)

```go
type Container struct {
  //+listType=map
  //+listMapKey=atomicStructField
  ListField []ListItem
}

//+mapType=atomic
type ListItem struct {
  atomicStructField AtomicStruct
}

//+mapType=atomic
type AtomicStruct struct {
  StringField string
}
```

**Comment by jpbetz** [comment]
xref https://github.com/kubernetes-sigs/structured-merge-diff/issues/163

**Comment by apelisse** [comment]
I think you've captured the interesting cases, thanks

**Comment by apelisse** [comment]
I said in the other issue that this is fixed, but I can't find what fixed it?

**Comment by Jefftree** [comment]
I think this issue can be split into two parts:

1. *Aliases:* The first two examples deal with using aliases for a type. This is not currently supported since we don't resolve aliases when generating the OpenAPI spec, but I think it should be a nice addition. The changes required to support this should be solely on the kube-openapi side to propagate certain keys up from their aliases. I did something similar with the propagation for defaulting, so implementing this shouldn't be too challenging. 
  
  > #### map typeref is tagged with +mapType=atomic (not supported or tested)
  > ```go
  > type Container struct {
  >   Field AtomicMapTyperef
  > }
  > 
  > // +mapType=atomic
  > type AtomicMapTyperef map[string]string
  > ```
  >
  > #### reference to map typeref is tagged with +mapType=atomic (not tested, seems to work)
  > ```go
  > type Container struct {
  >   //+mapType=atomic
  >   Field AtomicMapTyperef
  > }
  > 
  > type AtomicMapTyperef map[string]string
  > ```
  > 
  
  The use case for both of these looks valid, but I think we should disallow both of them to prevent potential misconfiguration. A map is by default "granular" according to the documentation, and I think we should enforce that the atomic annotation is kept throughout all aliases in order for us to treat the type as properly configured. For example, the second code block above is technically also equivalent to
  
  ```go
  type Container struct {
    //+mapType=atomic
    Field AtomicMapTyperef
  }
  
  //+mapType=granular
  type AtomicMapTyperef map[string]string
  ```
  
  which should obviously throw an error.

2. *Compositions of atomics in collections (lists, maps, etc)*: This seems to be a purely SMD feature (See https://github.com/kubernetes-sigs/structured-merge-diff/blob/17912732856ce1817c889fd8a8815083f6e0f826/typed/helpers.go#L210-L218).

> #### set of atomic structs (not tested, not sure if it works)
> ```go
> type Container struct {
>   //+listType=set
>   SetField []AtomicStruct
> }
> 
> //+mapType=atomic
> type AtomicStruct struct {
>   StringField string
> }
> ```

This is the same scenario as described in https://github.com/kubernetes-sigs/structured-merge-diff/issues/163 I believe. Sets containing atomic maps and atomic lists should be accepted, but at the moment it looks like we don't support it. I'm looking into what we'd need to change to support this.

**Comment by apelisse** [comment]
https://v1-18.docs.kubernetes.io/docs/reference/using-api/api-concepts/#merge-strategy

**Comment by Jefftree** [comment]
Discussions from yesterday:

1. The atomic property should be attached to a field and not a type. Aliases are fine, but only the atomic property in the field will be read. Adding an atomic property to an alias type should have no effect. I'll try to see if the documentation can be updated to make this more clear. The below code is the proper way to use atomic with aliases and already works with our code, so no additional code changes should be necessary.

```go
type Container struct {
  //+mapType=atomic
  Field AtomicMapTyperef
}

type AtomicMapTyperef map[string]string
```

2. Per https://v1-18.docs.kubernetes.io/docs/reference/using-api/api-concepts/#merge-strategy

> "atomic and set apply to lists with scalar elements only"

Based on the documentation we do not support sets with nonscalar elements. For now, there's not much of a use case to expand this support.
