### ISSUE TITLE
Adding Validation Constraints 

### ISSUE THREAD

**Issue by amir** [kubernetes/kube-openapi#26]
Hi,

I'm interested in tackling https://github.com/kubernetes/kubernetes/issues/8116 and https://github.com/kubernetes/kubernetes/issues/24562. I understand that this project wishes to remain free of Kubernetes particularities, and I also see there's an attempt at integrating kube-openapi at https://github.com/kubernetes/kubernetes/pull/55472.

So my question is if my end goal is to add enums to the generated swagger/openapi Json (or format regexp for Strings), should I start by adding the support to this project? Is this project intended to replace go-restful?

**Comment by mbohlool** [comment]
The project is not intend to replace go-restful but it would free us from go-restful by supporting OpenAPI. When we remove swagger 1.2 support from the main repo, we can use any routing library instead of go-restful. For validation and enum, you should add them here first, but for validation, we may need a more detailed design though I am not against adding regex validation to strings but it should also be connected to any validation code we already have.
