### ISSUE TITLE
Omit list_type_missing lint error from *List types

### ISSUE THREAD

**Issue by liggitt** [kubernetes/kube-openapi#281]
list_type is only useful when writing, and writes to *List types (containing metav1.ListMeta) are not written to

currently, every list type has a lint violation exception in place because of this, and every API promotion adds a new violation

**Comment by kerthcet** [comment]
Revisit this problem as we have to add the violations for each version. 
https://github.com/kubernetes/kubernetes/blob/55224e3bb94cdcfdd1fff5c5a4bdf84eeb67f949/api/api-rules/violation_exceptions.list#L346-L354

**Comment by alculquicondor** [comment]
The comment above is for `[]byte`

**Comment by Jefftree** [comment]
Based on the lint rules, it looks like if ListMeta is embedded, the list type should not need to be included. (https://github.com/kubernetes/kube-openapi/blob/master/pkg/generators/rules/idl_tag.go#L29-L33)

For https://github.com/kubernetes/kubernetes/pull/108445, the error is a bit cryptic, it should be a list type should not be included error rather than a list type missing error.

For https://github.com/kubernetes/kubernetes/pull/110534, ListMeta is not embedded and a listType annotation is required. It looks like this has already been added for v1 (https://github.com/kubernetes/kubernetes/blob/master/staging/src/k8s.io/kube-scheduler/config/v1/types.go#L381)
