### ISSUE TITLE
Integration tests should fail if generated openapi file is updated

### ISSUE THREAD

**Issue by Jefftree** [kubernetes/kube-openapi#294]
https://github.com/kubernetes/kube-openapi/pull/289#discussion_r832468565

**Comment by jiahuif** [comment]
In https://github.com/kubernetes/kube-openapi/blob/master/test/integration/integration_suite_test.go

The code-gen runs during BeforeSuite, which will have already overwritten existing generated files. During the `openapi-gen --verify` step, the verification will always pass because the expected content is already written to disk.
